sudo: required
services:
    - docker

before_install:
    - docker build -t maheshdwaghmare/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true maheshdwaghmare/frontend npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-101752226129"
    bucket_path: "frontend1"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"