language: node_js
sudo: required
services:
    - docker

before_install:
    - docker build -t maheshdwaghmare/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true maheshdwaghmare/frontend npm run test